language: go
go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - master

install:
  - go get -v github.com/mooncaker816/go-calendar/...
script: 
  - go build -v
  - go test -v -cover -race ./...